variables:
  GIT_SUBMODULE_STRATEGY: recursive

firmware:
  image: debian:stable
  before_script:
    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq && apt-get install -y -qq make cmake git wget flex bison gperf python3 python3-pip python3-setuptools python-is-python3 libffi-dev libssl-dev
    - git submodule update --init --recursive
    - git clone --depth=1 --recursive --branch v3.3.6 https://github.com/espressif/esp-idf.git
    - export IDF_PATH="$(readlink -f esp-idf)"
    - pip3 install -r $IDF_PATH/requirements.txt
    - sed -i '/^#include <protocomm_ble.h>$/d' $IDF_PATH/components/wifi_provisioning/include/wifi_provisioning/scheme_ble.h
    - wget -qO- https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-97-gc752ad5-5.2.0.tar.gz | tar xvz
    - export PATH="$PATH:$(readlink -f xtensa-esp32-elf/bin)"
  script:
    - mkdir -p firmware/build
    - cd firmware/build
    - cmake ..
    - make
    - make flash || true
  artifacts:
    paths:
      - firmware/build/bootloader/bootloader.bin
      - firmware/build/partition_table/partition-table.bin
      - firmware/build/timecube.bin
      - firmware/components/arduino/tools/esptool.py

